FROM node:20 AS builder

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package*.json /.

RUN npm install

COPY . .

RUN npm run build 



FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]