name : Test Workflow

on :
    push :
        branches :
        - main

jobs :
    build-and-push :
        runs-on : ubuntu-latest
        steps :
        - name : clone repo to runner 
          uses : actions/checkout@v4


        - name : ls  
          run : ls -l

        

        - name : build frontend image 
          run : docker build -t linkedin-frontend ./frontend
        
        - name : build backend image
          run : docker build -t linkedin-backend ./backend

        